### ISSUE TITLE
RFE: Support for the keptn development versions

### ISSUE THREAD

**Issue by shivam-Purohit** [keptn-sandbox/action-install-keptn#6]
**Problem statement.**

   
   As the keptn version  0.20.0-next.0 is recently released  , keptn install shall also support the development versions as well. 
    That will help to check the compatibility of the new version with the other components  

**Describe the solution you'd like**

 ```
     helm install keptn keptn/keptn --wait --create-namespace -n ${{ inputs.KEPTN_NAMESPACE}} -f values.yaml --version "${{ 
     inputs.KEPTN_VERSION }}" --devel
```
   As  @vadasambar mentioned --devel shall support the development versions.
   I think its a good temporary solution until the release of the stable version 

**Describe alternatives you've considered**

   Alternatively we can wait for the stable version to release

**Comment by vadasambar** [comment]
@shivam-Purohit can you update the title :pray:
